export default () => ({
  questions: [],
  activeCategory: null,
  kidsMode: false,
  categories: [
    {
      slug: 'geography',
      name: 'Geografía',
      kids: false,
      color: 'bg-blue-500',
      openTriviaIds: [22],
    },
    {
      slug: 'geography',
      name: 'Ciencias Sociales',
      kids: true,
      color: 'bg-blue-500',
    },
    {
      slug: 'entertainment',
      name: 'Entretenimiento',
      kids: false,
      color: 'bg-pink-500',
      openTriviaIds: [10, 11, 12, 13, 14, 15, 16],
    },
    {
      slug: 'entertainment',
      name: 'Dibujos Animados',
      kids: true,
      color: 'bg-pink-500',
    },
    {
      slug: 'history',
      name: 'Historia',
      kids: false,
      color: 'bg-yellow-500',
      openTriviaIds: [23],
    },
    {
      slug: 'english',
      name: 'Inglés',
      kids: true,
      color: 'bg-yellow-500',
    },
    {
      slug: 'art',
      name: 'Arte y Literatura',
      kids: false,
      color: 'bg-yellow-800',
      openTriviaIds: [25],
    },
    {
      slug: 'art',
      name: 'Adivinanzas',
      kids: true,
      color: 'bg-yellow-800',
    },
    {
      slug: 'science',
      name: 'Ciencia y Naturaleza',
      kids: false,
      color: 'bg-green-500',
      openTriviaIds: [17],
    },
    {
      slug: 'science',
      name: 'Mates y Ciencias',
      kids: true,
      color: 'bg-green-500',
    },
    {
      slug: 'sports',
      name: 'Deportes',
      kids: false,
      color: 'bg-orange-500',
      openTriviaIds: [21],
    },
    {
      slug: 'sports',
      name: 'Deportes',
      kids: true,
      color: 'bg-orange-500',
    },
  ],
})
